-- Academic Records Database in Oracle SQL
-- schema.sql
-- Defines tables and relational constraints for the academic records system

------------------------------------------------------------
-- LOOKUP TABLES
------------------------------------------------------------

create table coursemode (
   mode_id  number generated by default as identity primary key,
   modename varchar2(50) not null unique
);

create table term (
   term_id   number generated by default as identity primary key,
   termname  varchar2(50) not null unique,
   startdate date not null,
   enddate   date not null,
   constraint chk_term_dates check ( startdate < enddate )
);

create table coursestatus (
   status_id  number generated by default as identity primary key,
   statusname varchar2(30) not null unique
);

create table studentstatus (
   studentstatus_id number generated by default as identity primary key,
   statusname       varchar2(20) not null unique
);

------------------------------------------------------------
-- CORE ENTITY TABLES
------------------------------------------------------------

create table faculty (
   faculty_id           number generated by default as identity primary key,
   firstname            varchar2(50) not null,
   lastname             varchar2(50) not null,
   title                varchar2(20),
   officephonenumber    varchar2(15) not null,
   homephonenumber      varchar2(15),
   mailingaddressline1  varchar2(100) not null,
   mailingaddressline2  varchar2(100),
   mailingcity          varchar2(50) not null,
   mailingstate         char(2) not null,
   mailingzip           varchar2(10) not null,
   officeaddressline1   varchar2(100) not null,
   officeaddressline2   varchar2(100),
   officecity           varchar2(50) not null,
   officestate          char(2) not null,
   officezip            varchar2(10) not null,
   supervisorfaculty_id number,
   constraint chk_faculty_state_length
      check ( length(mailingstate) = 2
         and length(officestate) = 2 ),
    -- Self referencing relationship to model faculty supervision
   constraint fk_faculty_supervisor foreign key ( supervisorfaculty_id )
      references faculty ( faculty_id )
);

create table department (
   department_id            number generated by default as identity primary key,
   departmentname           varchar2(100) not null unique,
   chairfaculty_id          number not null,
   associatechairfaculty_id number,
   constraint fk_dept_chair foreign key ( chairfaculty_id )
      references faculty ( faculty_id ),
   constraint fk_dept_assoc_chair foreign key ( associatechairfaculty_id )
      references faculty ( faculty_id ),
   constraint chk_dept_chair_diff check ( chairfaculty_id <> associatechairfaculty_id )
);

create table student (
   student_id          number generated by default as identity primary key,
   firstname           varchar2(50) not null,
   lastname            varchar2(50) not null,
   birthdate           date not null,
   email               varchar2(100) not null unique,
   pronouns            varchar2(30),
   phonenumber         varchar2(15) not null,
   mailingaddressline1 varchar2(100) not null,
   mailingaddressline2 varchar2(100),
   mailingcity         varchar2(50) not null,
   mailingstate        char(2) not null,
   mailingzip          varchar2(10) not null,
   faculty_id          number not null,
   matriculationdate   date not null,
   graduationdate      date,
   constraint chk_student_state_length check ( length(mailingstate) = 2 ),
   constraint fk_student_faculty foreign key ( faculty_id )
      references faculty ( faculty_id )
);

------------------------------------------------------------
-- COURSE, SECTION, AND ENROLLMENT TABLES
------------------------------------------------------------

create table course (
   coursenumber             varchar2(8) primary key,
   fulltitle                varchar2(100) not null,
   shorttitle               varchar2(40) not null,
   description              varchar2(4000) not null,
   learningoutcomes         varchar2(4000),
   prerequisitecoursenumber varchar2(8),
   responsiblefaculty_id    number,
   constraint chk_shorttitle_length check ( length(shorttitle) <= 40 ),
    -- Self referencing relationship to model course prerequisites
   constraint fk_course_prereq foreign key ( prerequisitecoursenumber )
      references course ( coursenumber ),
   constraint fk_course_responsible_faculty foreign key ( responsiblefaculty_id )
      references faculty ( faculty_id )
);

create table section (
   section_id    number generated by default as identity primary key,
   coursenumber  varchar2(8) not null,
   sectionnumber varchar2(10) not null,
   faculty_id    number not null,
   term_id       number not null,
   mode_id       number not null,
   constraint fk_section_course foreign key ( coursenumber )
      references course ( coursenumber ),
   constraint fk_section_faculty foreign key ( faculty_id )
      references faculty ( faculty_id ),
   constraint fk_section_term foreign key ( term_id )
      references term ( term_id ),
   constraint fk_section_mode foreign key ( mode_id )
      references coursemode ( mode_id ),
   constraint uq_section_unique unique ( coursenumber,
                                         term_id,
                                         sectionnumber )
);

create table enrollment (
   enrollment_id number generated by default as identity primary key,
   student_id    number not null,
   section_id    number not null,
   status_id     number not null,
   constraint fk_enrollment_student foreign key ( student_id )
      references student ( student_id ),
   constraint fk_enrollment_section foreign key ( section_id )
      references section ( section_id ),
   constraint fk_enrollment_status foreign key ( status_id )
      references coursestatus ( status_id ),
    -- Prevents duplicate enrollment in the same section
   constraint uq_enrollment_unique unique ( student_id,
                                            section_id )
);

------------------------------------------------------------
-- STUDENT STATUS HISTORY
------------------------------------------------------------

create table studentstatushistory (
   history_id       number generated by default as identity primary key,
   student_id       number not null,
   studentstatus_id number not null,
   statuschangedate date not null,
   constraint fk_hist_student foreign key ( student_id )
      references student ( student_id ),
   constraint fk_hist_status foreign key ( studentstatus_id )
      references studentstatus ( studentstatus_id ),
   constraint uq_student_status_history unique ( student_id,
                                                 studentstatus_id,
                                                 statuschangedate )
);

------------------------------------------------------------
-- GRADUATE THESIS AND COMMITTEE
------------------------------------------------------------

create table graduatethesis (
    -- Student_ID serves as both the primary key and foreign key,
    -- allowing at most one thesis record per student
   student_id              number primary key,
   thesistitle             varchar2(200) not null,
   studytype               varchar2(20) not null,
   irb_required            char(1) check ( irb_required in ( 'Y',
                                                  'N' ) ),
   irb_approvaldate        date,
   proposaldefensedate     date,
   proposalapproved        char(1) check ( proposalapproved in ( 'Y',
                                                          'N' ) ),
   thesisdefensedate       date,
   thesisapproved          char(1) check ( thesisapproved in ( 'Y',
                                                      'N' ) ),
   thesisadvisorfaculty_id number not null,
   constraint chk_study_type check ( studytype in ( 'Theoretical',
                                                    'Empirical' ) ),
   constraint fk_gradthesis_student foreign key ( student_id )
      references student ( student_id ),
   constraint fk_gradthesis_advisor foreign key ( thesisadvisorfaculty_id )
      references faculty ( faculty_id )
);

create table thesiscommitteemember (
   committeemember_id number generated by default as identity primary key,
   student_id         number not null,
   faculty_id         number not null,
   ischair            char(1) not null check ( ischair in ( 'Y',
                                                 'N' ) ),
   constraint fk_tcm_student foreign key ( student_id )
      references student ( student_id ),
   constraint fk_tcm_faculty foreign key ( faculty_id )
      references faculty ( faculty_id ),
    -- Prevents the same faculty member from being assigned
    -- more than once to the same student's thesis committee
   constraint uq_tcm_student_faculty unique ( student_id,
                                              faculty_id )
);